### PR TITLE
Fixes problems with modal open/close.

### LINKED ISSUE #16: Clicking the Add Media button after image insert does not work
Once an image is inserted the Add Media button does not perform an action. To get back to the Grid you have to Move to Trash or Publish. 

For testing purposes the ideal scenario would be for the Add Media button to open the Grid and allow the adding of an additional image.

Alternately for testing purposes clicking the Add Media button after an image has been added should clear the original image and start the process over.

This addresses the common scenario that the tester wants to do something again immediately after adding the first image.

### PR DESCRIPTION
**Pull request by aymanalzarrad**
Disable the "$scope.secondtime" and make sure to reset the route path on modal close. Fixes #16.

### CODE REVIEW

**Comment by PabloPerea** [comment]
Hi!
It was created to solve "go back" from "full width" and from "upload". If you open modal, when it's already opened, thumbnails dissapear.
We can put that value to 0 when closing the modal, and it will allow open it again.

**Comment by aymanalzarrad** [comment]
Ah ok, I see... I think I could propose a fix for that.

**Comment by PabloPerea** [comment]
Probably is enough with checking if it is already opened.

**Comment by aymanalzarrad** [comment]
Yeah, I just pushed a simple class check that will check if the modal has the class 'open' before trying to open it.

**Comment by PabloPerea** [comment]
Great! Easier that way.
:-)

**Pull request merged**
